[ENH] Added Flag to save `LogFile`
neurobagel/api pull request #281
Opened 2024-02-27 21:34 UTC by samadpls

- Closes #250 

Changes proposed in this pull request:

-  Added flag to save log 

## Checklist

- [ ] PR has an interpretable title with a prefix (`[ENH]`, `[FIX]`, `[REF]`, `[TST]`, `[CI]`, `[MNT]`, `[INF]`, `[MODEL]`, `[DOC]`) _(see https://neurobagel.org/contributing/pull_requests for more info)_
- [ ] PR has a label for the release changelog or `skip-release` (to be applied by maintainers only)
- [ ] PR links to GitHub issue with mention `Closes #XXXX`
- [ ] Tests pass
- [ ] Checks pass

For new features:
- [ ] Tests have been added

For bug fixes:
- [ ] There is at least one test that would fail under the original bug conditions.

2024-02-28 20:00 UTC, alyssadai requested changes
Thanks a lot for the PR @samadpls! 🎉

This is looking good, though I think a few more changes are needed for full functionality of your new `--log-output` flag. See my comments/suggestions below, and feel free to let me know if you have any questions!

Please re-request a review once you have addressed the feedback.

2024-03-01 11:42 UTC, samadpls commented
Hi @alyssadai,
Thank you for your review 😋. I have implemented the suggested changes and addressed all the comments. 
Thanks again!

2024-03-04 17:02 UTC, alyssadai reviewed
Hey @samadpls, thanks for the changes!

Two final suggestions below, then I think this is good to be merged 🧑‍🍳

2024-03-04 17:02 UTC, alyssadai commented on add_data_to_graph.sh
> +    fi
```suggestion
```

This `if` block shouldn't be necessary: the logic for the default log file and empty arg handling is handled by the argument parsing code in the argbash block above.

2024-03-04 17:02 UTC, alyssadai commented on add_data_to_graph.sh
> +    main >> "$log_file"
```suggestion
    main > "$log_file"
```
for easier separation of logs from different runs

2024-03-04 17:32 UTC, alyssadai commented
Looks great, thanks a lot for your contribution @samadpls!

2024-03-04 17:33 UTC, alyssadai commented
Oops, accidentally closed instead of merged.

2024-03-04 17:33 UTC, alyssadai approved these changes

2024-03-04 17:36 UTC, merged